name = "py-backend"
compatibility_date = "2024-01-01"

# This is a required field for Pages projects
pages_build_output_dir = "."

# Environment variables
[vars]
ALLOWED_ORIGIN = "https://smith-frontend.vercel.app"

# Build configuration
[build]
command = "pip install -r requirements.txt"

# Functions configuration
[functions]
directory = "functions"

# Routes configuration
[routes]
pattern = "/api/*"
script = "api.py"

[site]
bucket = "./"